# Generated by Django 2.2.6 on 2019-11-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191108_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.IntegerField(default=0),
        ),
    ]
