# Generated by Django 2.2.6 on 2019-12-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
