# Generated by Django 2.2.6 on 2019-12-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
