# Generated by Django 2.2.6 on 2019-12-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_auto_20191205_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='community',
        ),
        migrations.AddField(
            model_name='comment',
            name='community',
            field=models.ManyToManyField(to='communities.Community'),
        ),
    ]
