# Generated by Django 2.2.6 on 2019-12-05 09:25

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20191205_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='comment',
            name='community',
        ),
        migrations.AddField(
            model_name='comment',
            name='community',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
