# Generated by Django 2.2.6 on 2019-12-05 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0007_auto_20191205_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='community',
        ),
        migrations.AddField(
            model_name='comment',
            name='community',
            field=models.ManyToManyField(to='communities.Community'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
