# Generated by Django 2.2.6 on 2019-12-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_auto_20191205_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=1200),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='community',
        ),
        migrations.AddField(
            model_name='comment',
            name='community',
            field=models.CharField(default='admin', max_length=120),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(default='aritra002', max_length=120),
            preserve_default=False,
        ),
    ]
