# Generated by Django 2.2.6 on 2019-11-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
                ('seniority', models.CharField(blank=True, max_length=120, null=True)),
                ('employment', models.CharField(blank=True, max_length=120, null=True)),
                ('about_us', models.URLField(blank=True, max_length=120, null=True)),
                ('role', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
